model_type: ft_transformer
experiment_name: ftt

model: ft_transformer
learning_rate: 0.0003
weight_decay: 0.005
batch_size: 32
epochs: 70

data: processed
use_ple: false
split_method: customer_id
train_size: 0.8
