model_type: resnet
experiment_name: resnet_ple

model: resnet_base
d_main: 128
d_hidden: 256
n_blocks: 3
dropout_first: 0.4
dropout_second: 0.0
learning_rate: 0.00002
weight_decay: 0.001
batch_size: 25

data: processed
use_ple: true
ple_n_bins: 20
split_method: customer_id
train_size: 0.8
